apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq
  labels:
    app: rabbit-mq
    type: infra
spec:
  type: NodePort
  ports:
  - name: queue
    port: 5672
    targetPort: 5672
    nodePort: 30100
    protocol: TCP
  - name: managment
    port: 15672
    targetPort: 15672
    nodePort: 30101
    protocol: TCP
  selector:
    app: rabbit-mq
