apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: observability
  source:
    directory:
      jsonnet: { }
      recurse: true
    repoURL: https://github.com/jmajaca/show-off.git
    targetRevision: devops
    path: devops/applications/observability/jaeger
  destination:
    server: https://kubernetes.default.svc
    namespace: show-off
  syncPolicy:
    automated: { }