apiVersion: v1
kind: Service
metadata:
  name: postgre-db
  labels:
    app: postgre-db
    type: infra
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30103
    protocol: TCP
  selector:
    app: postgre-db
