apiVersion: apps/v1
kind: Deployment
metadata:
  name: detection-api
  labels:
    app: detection-api
    type: backend-python
spec:
  selector:
    matchLabels:
      app: detection-api
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: detection-api
        type: backend-python
    spec:
      containers:
      - name: detection-api
        image: spaladium/detection-api
        env:
          - name: CTPN_WEIGHTS_FILE
            value: /config/weights/CTPN.pth
        volumeMounts:
          - mountPath: /config/weights/
            name: k8s-local-volume
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
        - name: k8s-local-volume
          hostPath:
            path: /var/kubernetes