apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: default-config
      namespace: iskon-infra
    data:
      default.conf: |
        http {
        
          upstream backend {
            server show-off-api.show-off.svc.cluster.local;
            server show-off-api-go.show-off.svc.cluster.local;
          }
          
          server {
            location / {
              proxy_pass http://backend;
            }
          }
        
        }
metadata:
  resourceVersion: ""