apiVersion: v1
kind: List
items:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: postgre-db-allow-show-off
    spec:
      podSelector:
        matchLabels:
          app: postgre-db
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  namespace: show-off
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: rabbit-mq-allow-show-off
    spec:
      podSelector:
        matchLabels:
          app: rabbit-mq
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  namespace: show-off
metadata:
  resourceVersion: ""