apiVersion: v1
kind: Service
metadata:
  name: image-api
  labels:
    app: image-api
    type: backend-java
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30003
    protocol: TCP
  selector:
    app: image-api
