apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-off-api-go
  labels:
    app: show-off-api-go
    type: backend-golang
spec:
  selector:
    matchLabels:
      app: show-off-api-go
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: show-off-api-go
        type: backend-golang
    spec:
      containers:
      - name: show-off-api-go
        image: spaladium/show-off-api-go
        env:
          - name: DETECTION_API_URL
            valueFrom:
              configMapKeyRef:
                name: internal-urls
                key: detection_api_url
          - name: RECOGNITION_API_URL
            valueFrom:
              configMapKeyRef:
                name: internal-urls
                key: recognition_api_url
          - name: QUEUE_HOST
            valueFrom:
              configMapKeyRef:
                name: queues
                key: host
          - name: QUEUE_PORT
            valueFrom:
              configMapKeyRef:
                name: queues
                key: port
          - name: QUEUE_VIRTUAL_HOST
            valueFrom:
              configMapKeyRef:
                name: queues
                key: virtual_host
          - name: QUEUE_EXCHANGE
            valueFrom:
              configMapKeyRef:
                name: queues
                key: exchange
          - name: IMAGE_QUEUE_NAME
            valueFrom:
              configMapKeyRef:
                name: queues
                key: image_queue
          - name: IMAGE_DATA_QUEUE_NAME
            valueFrom:
              configMapKeyRef:
                name: queues
                key: image_data_queue
          - name: TEXT_CORRECTION_QUEUE_NAME
            valueFrom:
              configMapKeyRef:
                name: queues
                key: text_correction_queue
          - name: QUEUE_USERNAME
            valueFrom:
              secretKeyRef:
                name: show-off-api-rabbit-mq-credentials
                key: username
          - name: QUEUE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: show-off-api-rabbit-mq-credentials
                key: password
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
