apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: documentation-ui
  namespace: argocd
spec:
  project: show-off
  source:
    directory:
      jsonnet: { }
      recurse: true
    repoURL: git@github.com:jmajaca/show-off.git
    targetRevision: devops
    path: devops/applications/show-off/documentation-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: show-off
  syncPolicy:
    automated: { }