apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: show-off-ui
  namespace: show-off
spec:
  project: show-off
  source:
    repoURL: git@github.com:jmajaca/show-off.git
    targetRevision: devops
    path: devops/applications/show-off/show-off-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: show-off