apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentry
  namespace: argocd
spec:
  project: sentry
  source:
    directory:
      jsonnet: { }
      recurse: true
    repoURL: git@github.com:jmajaca/show-off.git
    targetRevision: devops
    path: devops/administration/sentry
  destination:
    server: https://kubernetes.default.svc
    namespace: sentry
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true