apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: show-off
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: git@github.com:jmajaca/show-off.git
    targetRevision: devops
    path: devops/administration/show-off
  destination:
    server: https://kubernetes.default.svc
    namespace: show-off