apiVersion: apps/v1
kind: Deployment
metadata:
  name: recognition-api
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  labels:
    app: recognition-api
    type: backend-python
spec:
  selector:
    matchLabels:
      app: recognition-api
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: recognition-api
        type: backend-python
    spec:
      containers:
      - name: recognition-api
        image: spaladium/recognition-api
        env:
          - name: MODEL_WEIGHTS_PATH
            value: /config/weights/CRNN.pth
        volumeMounts:
          - mountPath: /config/weights/
            name: k8s-local-volume
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
        - name: k8s-local-volume
          hostPath:
            path: /var/kubernetes