apiVersion: v1
kind: Service
metadata:
  name: detection-api
  labels:
    app: detection-api
    type: backend-python
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30003
    protocol: TCP
  selector:
    app: detection-api
