apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: internal-urls
    data:
      detection_api_url: "http://detection-api.show-off.svc.cluster.local:5000"
      recognition_api_url: "http://recognition-api.show-off.svc.cluster.local:5000"
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: queues
    data:
      host: rabbit-mq.show-off-infra.svc.cluster.local
      port: '5672'
      virtual_host: show-off
      exchange: ''
      image_queue: imageQueue
      image_data_queue: imageDataQueue
      text_correction_queue: textCorrectionQueue
metadata:
  resourceVersion: ""
