apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-off-ui
  labels:
    app: show-off-ui
    type: frontend
spec:
  selector:
    matchLabels:
      app: show-off-ui
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: show-off-ui
        type: frontend
    spec:
      containers:
      - name: show-off-ui
        image: spaladium/show-off-ui
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /show-off/health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5