apiVersion: v1
kind: Service
metadata:
  name: show-off-ui
  labels:
    app: show-off-ui
    type: frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
  selector:
    app: show-off-ui
