name: ci-cd

on:
  push:
    branches:
      - 'frontend'
      - 'show-off-api'
      - 'detection'
      - 'ocr-model'
      - 'image-api'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check if project is show-off-ui
        if: github.ref_name == 'frontend'
        run: |
          echo "PROJECT=show-off-ui" >> $GITHUB_ENV
          echo "PROJECT_CONTEXT=show-off-ui" >> $GITHUB_ENV
          echo "LANGUAGE=typescript" >> $GITHUB_ENV
      -
        name: Check if project is show-off-api
        if: github.ref_name == 'show-off-api'
        run: |
          echo "PROJECT=show-off-api" >> $GITHUB_ENV
          echo "PROJECT_CONTEXT=show-off-api/python" >> $GITHUB_ENV
          echo "LANGUAGE=python" >> $GITHUB_ENV
      -
        name: Check if project is recognition-api
        if: github.ref_name == 'ocr-model'
        run: |
          echo "PROJECT=recognition-api" >> $GITHUB_ENV
          echo "PROJECT_CONTEXT=recognition/python" >> $GITHUB_ENV
          echo "LANGUAGE=python" >> $GITHUB_ENV
      -
        name: Check if project is detection-api
        if: github.ref_name == 'detection'
        run: |
          echo "PROJECT=detection-api" >> $GITHUB_ENV
          echo "PROJECT_CONTEXT=detection/python" >> $GITHUB_ENV
          echo "LANGUAGE=python" >> $GITHUB_ENV
      -
        name: Check if project is image-api
        if: github.ref_name == 'image-api'
        run: |
          echo "PROJECT=image-api" >> $GITHUB_ENV
          echo "PROJECT_CONTEXT=image-api" >> $GITHUB_ENV
          echo "LANGUAGE=java" >> $GITHUB_ENV
      -
        id: current_project
        name: Sharing current project with other jobs
        run: echo "::set-output name=project::${{ env.PROJECT }}"
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      -
        name: Set up JDK
        if: ${{ env.LANGUAGE }} == 'java'
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      -
        name: Gradle build
        if: ${{ env.LANGUAGE }} == 'java'
        run: cd ${{ env.PROJECT_CONTEXT }} && ./gradlew build && java -jar build/libs/gs-spring-boot-docker-0.1.0.jar
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT }}:latest
          context: ${{ env.PROJECT_CONTEXT }}
    outputs:
      project: ${{ steps.current_project.outputs.project }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Rollout application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            minikube kubectl -- rollout restart deployment ${{ needs.build.outputs.project }} --namespace=show-off
