name: ci-cd

on:
  push:
    branches:
      - 'frontend'
      - 'show-off-api'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if project is show-off-ui
        if: github.ref_name == 'frontend'
        run: echo "PROJECT=show-off-ui" >> $GITHUB_ENV
      -
        name: Check if project is show-off-api
        if: github.ref_name == 'show-off-api'
        run: echo "PROJECT=show-off-api" >> $GITHUB_ENV
      -
        id: current_project
        name: Sharing current project with other jobs
        run: echo "::set-output name=project::${{ env.PROJECT }}"
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.PROJECT }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PROJECT }}:latest
          context: ${{ env.PROJECT }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Rollout application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            minikube kubectl -- rollout restart deployment ${{ jobs.build.steps.current_project.outputs.project }}
